### ISSUE TITLE
reimplement host status change

### ISSUE THREAD

**Issue by cprerovsky** [cprerovsky/moonar-lander#1]
Currently the first client connecting automatically gains host status, which is fragile. Change implementation.

**Comment by cprerovsky** [comment]
```
[supervisor] connect client TmE3laTVsBYwO4ugcW0G
[supervisor] C:\git\moonar-lander\node_modules\ws\lib\WebSocket.js:219
[supervisor]     else throw new Error('not opened');
[supervisor]          ^
[supervisor]
[supervisor] Error: not opened
[supervisor]     at WebSocket.send (C:\git\moonar-lander\node_modules\ws\lib\WebSocket.js:219:16)
[supervisor]     at message (C:\git\moonar-lander\backend\build\index.js:37:43)
[supervisor]     at WebSocket.ws.on (C:\git\moonar-lander\backend\build\index.js:28:32)
[supervisor]     at emitTwo (events.js:106:13)
[supervisor]     at WebSocket.emit (events.js:191:7)
[supervisor]     at Receiver.ontext (C:\git\moonar-lander\node_modules\ws\lib\WebSocket.js:841:10)
[supervisor]     at C:\git\moonar-lander\node_modules\ws\lib\Receiver.js:536:18
[supervisor]     at C:\git\moonar-lander\node_modules\ws\lib\Receiver.js:368:7
[supervisor]     at C:\git\moonar-lander\node_modules\ws\lib\PerMessageDeflate.js:249:5
[supervisor]     at afterWrite (_stream_writable.js:388:3)
[supervisor]     at onwrite (_stream_writable.js:379:7)
[supervisor] [nodemon] app crashed - waiting for file changes before starting...
 
```

**Comment by cprerovsky** [comment]
fixed.
